In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('../opencv_data/lena.jpg') # 칼라
img[100, 200] = [255, 0, 0]

In [3]:
print(img[100, 200:210])

[[255   0   0]
 [116 115 207]
 [122 114 214]
 [107 103 198]
 [117 121 209]
 [112 119 204]
 [114 115 205]
 [116 109 206]
 [100 107 192]
 [108 112 201]]


In [7]:
img[100:400, 200:300] = [255, 0, 0]
img[100:400, 200:300]

array([[[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       ...,

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255,   0,   0],
        [255,   0,   0],
        [255,   0,   0],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

In [6]:
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()